### ISSUE TITLE
No convenient programmatic access to the search

### ISSUE THREAD

**Issue by mjdominus-ly** [haskellfoundation/error-message-index#350]
I want to set up a search macro for my browser's URL bar, so I can type `err blah` and have it go visit `https://errors.haskell.org/?q=blah`.

There doesn't seem to be any way to do that, because the search bar is an embedded JS thing with no API.

Ultimately there ought to be a real API where a program can post a string or error code and get back a description or a URL, but that would be a separate bug report.  All I am currently requesting is a distinct URL for each search.

**Comment by mjdominus-ly** [comment]
The Javascript can look at the query parameters and, if there are any,
prepopulate the input field with the query parameters instead of with the
placeholder text.

**Comment by david-christiansen** [comment]
Right - would this be sufficient for your use case?

**Comment by mjdominus-ly** [comment]
Yes, I think so.

**Comment by david-christiansen** [comment]
Great to hear!

**Comment by hasufell** [comment]
I have a similar problem, which might have a separate solution. I want a link to ALL GHCup errors. That doesn't have to be done with the filter, we could just have a subpage for grouping.

**Comment by BinderDavid** [comment]
This has been fixed by #387 If there is still some missing feature please shout :)
