### ISSUE TITLE
Allow to link to all errors of a specific tool

### ISSUE THREAD

**Issue by hasufell** [haskellfoundation/error-message-index#378]
Follow-up of https://github.com/haskellfoundation/error-message-index/issues/350#issuecomment-1382672906

I'd like to have a link such as https://errors.haskell.org/messages/GHCup that shows all and only GHCup errors.

**Comment by david-christiansen** [comment]
This would be nice!

**Comment by BinderDavid** [comment]
@hasufell The site is now online at https://errors.haskell.org/ghcup/ Thanks to @haglobah who implemented this feature :)
