### ISSUE TITLE
UI spacing off on footer

### ISSUE THREAD

**Issue by jzwood** [haskellfoundation/error-message-index#386]
Haskell logo and "generated with Jekyll" text are too tight with side of page on medium viewport. I think they should probably have the same margin as the containers above them.

<img width="823" alt="Screenshot 2023-02-28 at 9 31 56 AM" src="https://user-images.githubusercontent.com/13749324/221885456-a3094136-fdb5-42cd-9a8d-3a20fc68ca4f.png">

**Comment by david-christiansen** [comment]
I agree - thanks for noticing!
