### ISSUE TITLE
Some pages show empty "Enabled by" section for warning.

### ISSUE THREAD

**Issue by jhrcek** [haskellfoundation/error-message-index#389]
See for example on this page: https://errors.haskell.org/messages/GHC-90584/

![Screenshot from 2023-03-06 07-12-41](https://user-images.githubusercontent.com/2716069/223032702-715f7b83-f379-40da-81e8-22781ff91b93.png)

The root cause is that the [list of warning groups](https://github.com/haskellfoundation/error-message-index/blob/main/message-index/warning-sets/warning-sets-9.5.txt) (which can contain warning groups like -Wall, -Wcompat etc.) is empty for this warning. I think in such cases "Enabled by:" section should not be displayed.

**Comment by david-christiansen** [comment]
I agree. Should be an `if` in the template.

**Comment by jhrcek** [comment]
FIxed in https://github.com/haskellfoundation/error-message-index/pull/390
