### ISSUE TITLE
Optional explicit ordering of examples

### ISSUE THREAD

**Issue by david-christiansen** [haskellfoundation/error-message-index#438]
Talking with @VictorCMiraldo at lunch today about #436, we came to the conclusion that error docs should support optional ordering of examples (when the one writing the documentation has a particular idea about which examples are most likely to be relevant). The design we hit on would be extending the YAML block in an example's `index.md` to allow an optional field `order` that should contain an int. Examples can then be ordered by this field. Those without an order would come at the end (so absence is negative infinity) and anything with the same explicit `order` field would be displayed in some arbitrary order within the group.

**Comment by VictorCMiraldo** [comment]
Indeed, I'll give a quick stab at this before leaving Zurich!
