### ISSUE TITLE
Error messages for GHCup messages are missing header, title and footer

### ISSUE THREAD

**Issue by BinderDavid** [haskellfoundation/error-message-index#459]
![Screenshot 2023-09-01 at 12-32-44 https __errors haskell org](https://github.com/haskellfoundation/error-message-index/assets/18737248/e2b46867-1716-491f-aa61-60651bf1164e)

The error messages for GHCup currently look like above. I.e. all the CSS styling is missing.

**Comment by BinderDavid** [comment]
First guess: This has to do with the fact that there are no examples? 
We should allow that case, since there are probably a lot of errors for all kinds of tools where we cannot give a before/after example.

**Comment by david-christiansen** [comment]
What CSS would you expect here?

The text in question is not code in any particular language, so syntax highlighting doesn't seem appropriate. If we want to match the console output, then we'd have to manually annotate the text with the ANSI codes, which is definitely possible but quite annoying in a Markdown-drive workflow.

Basically, how would you expect this to look before you wanted to close this issue?

**Comment by BinderDavid** [comment]
I would at least expect the breadcrumbs and the title of the message above, and the footer with the Haskell logo below. I.e. something like https://errors.haskell.org/messages/GHC-00158/ but without the examples section.

**Comment by BinderDavid** [comment]
I have narrowed it down. With the following patch:
```console
--- a/message-index/messages/GHCup-05841/index.md
+++ b/message-index/messages/GHCup-05841/index.md
@@ -1,8 +1,5 @@
 ---
 title: A download failed
-summary: GHCup tried to download a tool, but the download failed with a subprocess exiting prematurely
-severity: error
-introduced: 0.1.19.0
 ---

```
I.e. if I remove the summary, severity and introduced field, I get at least the correct result which displays the header and footer.

**Comment by david-christiansen** [comment]
Now I get what you mean - thanks for being explicit. I was focused on the verbatim block, not the whole page!

I wonder if this is a bug in the new Hakyll release - does this happen if you build with 4.16.0?

**Comment by BinderDavid** [comment]
> Now I get what you mean - thanks for being explicit. I was focused on the verbatim block, not the whole page!
> 
> I wonder if this is a bug in the new Hakyll release - does this happen if you build with 4.16.0?

That seems to be it. I just checked with `hakyll 4-15.1.1` and it doesn't exhibit this problem.

**Comment by david-christiansen** [comment]
Thanks!

**Comment by BinderDavid** [comment]
Oh, I just checked. It cannot be the new scheduler,  ` 4.16.0` already seems to exhibit the bug, so it must have been introduced between `4.15` and `4.16`.
