### ISSUE TITLE
Use haskeline for create-message-template.hs

### ISSUE THREAD

**Issue by noughtmare** [haskellfoundation/error-message-index#499]
I noticed I cannot use my arrow keys to move the cursor when creating a new message. Delete also doesn't work properly over multiple lines.

The https://hackage.haskell.org/package/haskeline package provides a solution for these problems.

**Comment by BinderDavid** [comment]
Is there a way to specify this as a dependency in the header of the file somehow? Currently the README.md tells you to just use `runhaskell`, so how do we handle a dependency without a cabal file?

**Comment by jhrcek** [comment]
@BinderDavid you can have single-file scripts either using cabal
https://cabal.readthedocs.io/en/3.10/getting-started.html#run-a-single-file-haskell-script
or stack
https://docs.haskellstack.org/en/stable/scripts/
