### ISSUE TITLE
Machine Readable List of Errors

### ISSUE THREAD

**Issue by dylan-thinnes** [haskellfoundation/error-message-index#531]
I have a PR for this that I think does the job: https://github.com/haskellfoundation/error-message-index/pull/532

At HLS we'd like to link people to the error index, but only do so when it is actually documented in the index. For that we'd need some machine-readable and durable spec, I'd prefer JSON for selfish reasons, from which we can get the list of errors and a bit of their metadata.

We'd cache the lookup so as not to hammer HEI too much - this shouldn't affect Github Pages, be we should avoid too much load on the Haskell error index in case we ever need to move off of that onto our own solution.

More background on why we feel we need this and alternatives we've considered here: https://github.com/haskell/haskell-language-server/issues/4327

I've looked through the history and didn't find any mention of this, so I've been a bit presumptuous and opened an issue - sorry if this isn't the right place!

**Comment by BinderDavid** [comment]
Yes, that sounds very sensible. I will merge any sensible PR which implements this :)

**Comment by BinderDavid** [comment]
Closed in #532
